name: Waka Readme

on:
  schedule:
    # Runs at 12am IST
    - cron: '30 18 * * *'
  workflow_dispatch:
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: syavabrazzzers/syavabrazzzers@main
        with:
          WAKATIME_API_KEY: ${{ Actions.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ Actions.GH_TOKEN }}
          SHOW_OS: "True"
          SHOW_PROJECTS: "True"
