name: Waka Readme

on:
  schedule:
    # Runs at 12am IST
    - cron: '30 18 * * *'
  workflow_dispatch:
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    environment: secrets
    steps:
      - run: echo ${{secrets.WAKATIME_API_KEY}}
      - run: echo ${{env..WAKATIME_API_KEY}}
      - run: echo ${{vars..WAKATIME_API_KEY}}
#       - uses: syavabrazzzers/waka-widgets@main
#         with:
#           WAKATIME_API_KEY: ${{secrets.WAKATIME_API_KEY}}
#           GH_TOKEN: 'aboba2'
#           ZXC: 'aboba'
